
import React from "react";
import { Article } from "./Article";
import { T } from "../PartialTranslationParagraph";

export const CaptnBluebear = () => {
    return (
        <Article title="The 13 1/2 Lives of Capitain Bluebear">
            A life usually begins with birth - mine does <T w="nicht" />. At least I do <T w="nicht" /> know how I came into life. I could - theoretically - have been born from the foam of a wave or grown in a shell like a pearl. I might have fallen from the <T w="Himmel" />, in a shooting star, but all that is certain is that I was abandoned as a foundling in the middle of the ocean. My first memory is that I was floating in rough seas, naked and alone in a walnut shell, because I was originally very, very <T w="klein" />. I still remember a sound. It was a very big sound. No matter how <T w="klein" /> <T w="du" /> are, <T w="du" /> tend to overestimate things, but today I know that it was indeed the biggest sound in the world, generated by the most monstrous, dangerous and loudest water vortex in the seven seas - I had no idea that it was the dreaded Malmstrom I was looking at in my bowl. For me it was <T w="nur" /> a huge gurgling. Probably I thought (if <T w="du" /> could call it thinking) that it was probably the most natural state to drift naked in a nutshell on the open sea towards a deafening roar.
            <p>Excerpt from The 13 1/2 Lives of Capitain Bluebear by Walter Moers.</p>
        </Article>
    )
}